CREATE VIEW vw_user_group_rights AS
SELECT 
    ug.USER_GROUP_NAME,
    uo.USER_OBJECT_NAME,
    uo.USER_OBJECT_URL,
    CASE 
        WHEN uo.USER_OBJECT_URL = 'API_SCOPE' AND ugr.USER_GROUP_RIGHT_READ = 'Y' THEN uo.USER_OBJECT_NAME || ':Read'
        ELSE NULL 
    END AS USER_SCOPE_NAME_READ,
    CASE 
        WHEN uo.USER_OBJECT_URL = 'API_SCOPE' AND ugr.USER_GROUP_RIGHT_WRITE = 'Y' THEN uo.USER_OBJECT_NAME || ':Write'
        ELSE NULL 
    END AS USER_SCOPE_NAME_WRITE,
    CASE 
        WHEN uo.USER_OBJECT_URL = 'API_SCOPE' AND ugr.USER_GROUP_RIGHT_EXECUTE = 'Y' THEN uo.USER_OBJECT_NAME || ':Execute'
        ELSE NULL 
    END AS USER_SCOPE_NAME_EXECUTE,
    CASE 
        WHEN uo.USER_OBJECT_URL = 'API_SCOPE' AND ugr.USER_GROUP_RIGHT_DELETE = 'Y' THEN uo.USER_OBJECT_NAME || ':Delete'
        ELSE NULL 
    END AS USER_SCOPE_NAME_DELETE,
    ugu.USER_ID,
    ugu.API_USER_ID,
    ugu.API_CLIENT_ID,
    ugr.USER_GROUP_RIGHT_ID,
    ugr.USER_GROUP_ID,
    ugr.USER_OBJECT_ID,
    ugr.USER_GROUP_RIGHT_READ,
    ugr.USER_GROUP_RIGHT_WRITE,
    ugr.USER_GROUP_RIGHT_EXECUTE,
    ugr.USER_GROUP_RIGHT_DELETE,
    ugr.USER_GROUP_RIGHT_VALID_FROM
FROM
    USER_OBJECTS uo 
    INNER JOIN USER_GROUP_RIGHTS ugr ON uo.USER_OBJECT_ID = ugr.USER_OBJECT_ID AND ugr.USER_GROUP_RIGHT_VALID_TO IS NULL
    INNER JOIN USER_GROUPS ug ON ug.USER_GROUP_ID = ugr.USER_GROUP_ID AND ug.USER_GROUP_VALID_TO IS NULL 
    INNER JOIN USER_GROUP_USERS ugu ON ugu.USER_GROUP_ID = ugr.USER_GROUP_ID AND ugu.USER_GROUP_USERS_VALID_TO IS NULL;
