CREATE OR REPLACE VIEW vw_user_lookup AS
SELECT
    u.USER_ID,
    u.USER_PARENT_ID,
    u.USER_NAME,
    u.USER_EMAIL,
    u.USER_VALID_FROM,
    ud.USER_DETAILS_ID,
    up.USER_PASSWORD,
    ud.USER_DETAILS_SALUTATION,
    ud.USER_DETAILS_FIRSTNAME,
    ud.USER_DETAILS_LASTNAME,
    ud.USER_DETAILS_COMPANY,
    ud.USER_DETAILS_BIRTHDAY,
    ud.USER_DETAILS_GENDER,
    ud.USER_DETAILS_PHONE,
    ud.USER_DETAILS_FAX,
    ud.USER_DETAILS_MOBILE,
    ud.USER_DETAILS_MOBILE_NOTIFICATION,
    ud.USER_DETAILS_EMAIL,
    ud.USER_DETAILS_EMAIL_NOTIFICATION,
    ud.USER_DETAILS_PREFERRED_LANGUAGE
FROM
    "USER" u
    LEFT JOIN USER_DETAILS ud ON u.USER_ID = ud.USER_ID AND ud.USER_DETAILS_VALID_TO IS NULL
    JOIN USER_PASSWORDS up ON up.USER_ID = u.USER_ID AND up.USER_PASSWORD_VALID_TO IS NULL
WHERE
    u.USER_VALID_TO IS NULL;
