CREATE TABLE `COUNTRIES` (
    `COUNTRY_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `COUNTRY_NAME` VARCHAR(255),
    `COUNTRY_ISO_CODE` VARCHAR(3),
    `COUNTRY_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `COUNTRY_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `COUNTRY_CREATED_BY` INT NOT NULL,
    `COUNTRY_UPDATED_BY` INT,
    PRIMARY KEY (`COUNTRY_ID`)
) ENGINE = INNODB COMMENT = 'base table holding available country names & iso codes';