CREATE TABLE `ESG_MEASURES` (
    `ESG_MEASURE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ESG_MEASURE_PARENT_ID` INT UNSIGNED,
    `ESG_MEASURE_KEY` VARCHAR(20) NOT NULL,
    `ESG_MEASURE_STATUS` BOOLEAN,
    `ESG_MEASURE_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ESG_MEASURE_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `ESG_MEASURE_CREATED_BY` INT NOT NULL,
    `ESG_MEASURE_UPDATED_BY` INT,
    PRIMARY KEY (`ESG_MEASURE_ID`)
) ENGINE = INNODB COMMENT = 'listing all ESG questions / topics';