CREATE TABLE `ESG_QUESTIONAIRE_ANSWERS` (
    `ESG_QUESTIONAIRE_ANSWER_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ESG_QUESTIONAIRE_ID` INT UNSIGNED NOT NULL,
    `ESG_MEASURE_ID` INT UNSIGNED NOT NULL,
    `STAKEHOLDER_ID` INT UNSIGNED NOT NULL,
    `ESG_QUESTIONAIRE_ANSWER_PRIORITY` INT,
    `ESG_QUESTIONAIRE_ANSWER_STATUS` INT,
    `ESG_QUESTIONAIRE_ANSWER_COMMENTS` TEXT,
    `ESG_QUESTIONAIRE_ANSWER_COUNTRY_ISO` VARCHAR(2) NOT NULL,
    `ESG_QUESTIONAIRE_ANSWER_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ESG_QUESTIONAIRE_ANSWER_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `ESG_QUESTIONAIRE_ANSWER_CREATED_BY` INT NOT NULL,
    `ESG_QUESTIONAIRE_ANSWER_UPDATED_BY` INT,
    PRIMARY KEY (`ESG_QUESTIONAIRE_ANSWER_ID`),
    FOREIGN KEY (`ESG_QUESTIONAIRE_ID`) REFERENCES `ESG_QUESTIONAIRES` (`ESG_QUESTIONAIRE_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`STAKEHOLDER_ID`) REFERENCES `STAKEHOLDER` (`STAKEHOLDER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ESG_MEASURE_ID`) REFERENCES `ESG_MEASURES` (`ESG_MEASURE_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB COMMENT = 'detail data / descriptions for ESG measures in questionaires and topic lists';