CREATE TABLE `ESG_QUESTIONAIRES` (
    `ESG_QUESTIONAIRE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `QUESTIONAIRE_TYPE` VARCHAR(255),
    `PERSON_ID` INT UNSIGNED NOT NULL,
    `ORGANISATION_ID` INT UNSIGNED NOT NULL,
    `RELATED_ORGANISATION_ID` INT UNSIGNED NOT NULL,
    `QUESTIONAIRE_COMMENT` TEXT,
    `QUESTIONAIRE_DATE` DATE,
    `ESG_QUESTIONAIRE_ANSWER_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ESG_QUESTIONAIRE_ANSWER_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `ESG_QUESTIONAIRE_ANSWER_CREATED_BY` INT NOT NULL,
    `ESG_QUESTIONAIRE_ANSWER_UPDATED_BY` INT,
    PRIMARY KEY (`ESG_QUESTIONAIRE_ID`),
    FOREIGN KEY (`PERSON_ID`) REFERENCES `PERSONS` (`PERSON_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ORGANISATION_ID`) REFERENCES `ORGANISATIONS` (`ORGANISATION_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`RELATED_ORGANISATION_ID`) REFERENCES `ORGANISATIONS` (`ORGANISATION_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB COMMENT = 'detail data / descriptions for ESG measures in questionaires and topic lists';


/*

ALTER TABLE `ESG_QUESTIONAIRES`
ADD COLUMN `RELATED_ORGANISATION_ID` INT UNSIGNED,
ADD CONSTRAINT `fk_related_organisation_id`
    FOREIGN KEY (`RELATED_ORGANISATION_ID`) REFERENCES `ORGANISATIONS` (`ORGANISATION_ID`)
    ON DELETE RESTRICT ON UPDATE CASCADE;


*/