CREATE TABLE `ESG_MEASURE_DESCRIPTIONS` (
    `ESG_MEASURE_DESCRIPTION_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ESG_MEASURE_ID` INT UNSIGNED NOT NULL,
    `ESG_MEASURE_DESCRIPTION_SHORT_NAME` VARCHAR(80) NOT NULL,
    `ESG_MEASURE_DESCRIPTION` VARCHAR(255) NOT NULL,
    `ESG_MEASURE_DESCRIPTION_TOPIC` BOOLEAN,
    `ESG_MEASURE_DESCRIPTION_ANSWERS` TEXT,
    `ESG_MEASURE_DESCRIPTION_COUNTRY_ISO` VARCHAR(2) NOT NULL,
    `ESG_MEASURE_DESCRIPTION_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ESG_MEASURE_DESCRIPTION_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `ESG_MEASURE_DESCRIPTION_CREATED_BY` INT NOT NULL,
    `ESG_MEASURE_DESCRIPTION_UPDATED_BY` INT,
    PRIMARY KEY (`ESG_MEASURE_DESCRIPTION_ID`),
    FOREIGN KEY (`ESG_MEASURE_ID`) REFERENCES `ESG_MEASURES` (`ESG_MEASURE_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB COMMENT = 'detail data / descriptions for ESG measures in questionaires and topic lists';


/*

ALTER TABLE `ESG_MEASURE_DESCRIPTIONS`
ADD COLUMN `ESG_MEASURE_DESCRIPTION_SHORT_NAME` VARCHAR(80) NOT NULL;


*/