CREATE TABLE `ORGANISATION_SECTORS` (
    `ORGANISATION_SECTOR_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `SECTOR_ID` INT UNSIGNED NOT NULL,
    `ORGANISATION_ID` INT UNSIGNED NOT NULL,
    `ORGANISATION_SECTOR_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ORGANISATION_SECTOR_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `ORGANISATION_SECTOR_CREATED_BY` INT NOT NULL,
    `ORGANISATION_SECTOR_UPDATED_BY` INT,
    PRIMARY KEY (`ORGANISATION_SECTOR_ID`),
    FOREIGN KEY (`SECTOR_ID`) REFERENCES `SECTORS` (`SECTOR_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ORGANISATION_ID`) REFERENCES `ORGANISATIONS` (`ORGANISATION_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB COMMENT = 'relation table connecting organisations to sectors';