CREATE TABLE `ORGANISATIONS` (
    `ORGANISATION_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ORGANISATION_NAME` VARCHAR(255) NOT NULL,
    `ORGANISATION_VAT_ID` VARCHAR(50),
    `ORGANISATION_LEGAL_FORM` VARCHAR(255),
    `ORGANISATION_LEGAL_REGISTRATION_NUMBER` VARCHAR(255),
    `ORGANISATION_LEGAL_REGISTRY` VARCHAR(255),
    `ORGANISATION_LOGO_URL` VARCHAR(255),
    `ORGANISATION_PRIM_COLOR` VARCHAR(25),
    `ORGANISATION_SEC_COLOR` VARCHAR(25),
    `ORGANISATION_STREET` VARCHAR(255),
    `ORGANISATION_ZIP` VARCHAR(50),
    `ORGANISATION_STATE` VARCHAR(255),
    `ORGANISATION_CITY` VARCHAR(255),
    `ORGANISATION_COUNTRY_ISO` VARCHAR(2) NOT NULL,
    `ORGANISATION_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ORGANISATION_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `ORGANISATION_CREATED_BY` INT NOT NULL,
    `ORGANISATION_UPDATED_BY` INT,
    PRIMARY KEY (`ORGANISATION_ID`)
) ENGINE = INNODB COMMENT = 'base table holding organisation data';


/*

ALTER TABLE `ORGANISATIONS`
ADD `ORGANISATION_LOGO_URL` VARCHAR(255),
ADD `ORGANISATION_PRIM_COLOR` VARCHAR(25),
ADD `ORGANISATION_SEC_COLOR` VARCHAR(25);


*/