CREATE TABLE `ORGANISATION_PERSONS` (
    `ORGANISATION_PERSON_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `PERSON_ID` INT UNSIGNED NOT NULL,
    `ORGANISATION_PERSON_ROLE` VARCHAR(255),
    `ORGANISATION_PERSON_FUNCTION` VARCHAR(255),
    `STAKEHOLDER_ID` INT UNSIGNED NOT NULL,
    `ORGANISATION_ID` INT UNSIGNED NOT NULL,
    `ORGANISATION_PERSON_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `ORGANISATION_PERSON_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `ORGANISATION_PERSON_CREATED_BY` INT NOT NULL,
    `ORGANISATION_PERSON_UPDATED_BY` INT,
    PRIMARY KEY (`ORGANISATION_PERSON_ID`),
    FOREIGN KEY (`PERSON_ID`) REFERENCES `PERSONS` (`PERSON_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`STAKEHOLDER_ID`) REFERENCES `STAKEHOLDER` (`STAKEHOLDER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (`ORGANISATION_ID`) REFERENCES `ORGANISATIONS` (`ORGANISATION_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB COMMENT = 'relation table connecting organisations and persons with specific roles';

/*
Changesets

ALTER TABLE `ORGANISATION_PERSONS`
ADD COLUMN `ORGANISATION_PERSON_FUNCTION` VARCHAR(255) AFTER `ORGANISATION_PERSON_ROLE`;





*/