CREATE TABLE `SDG` (
    `SDG_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `SDG_PARENT_ID` INT UNSIGNED,
    `SDG_NACE` VARCHAR(255),
    `SDG_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `SDG_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `SDG_CREATED_BY` INT NOT NULL,
    `SDG_UPDATED_BY` INT,
    PRIMARY KEY (`SDG_ID`)
) ENGINE = INNODB COMMENT = 'base table for Sustainable Development Goals';