CREATE TABLE `SDG_DESCRIPTIONS` (
    `SDG_NAME_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `SDG_ID` INT UNSIGNED NOT NULL,
    `SDG_NAME` VARCHAR(255) NOT NULL,
    `SDG_SHORT_NAME` VARCHAR(255) NOT NULL,
    `SDG_NAME_COUNTRY_ISO` VARCHAR(2) NOT NULL,
    `SDG_NAME_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `SDG_NAME_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `SDG_NAME_CREATED_BY` INT NOT NULL,
    `SDG_NAME_UPDATED_BY` INT,
    PRIMARY KEY (`SDG_NAME_ID`),
    FOREIGN KEY (`SDG_ID`) REFERENCES `SDG` (`SDG_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB COMMENT = 'base table for Sustainable Development Goal (SDG) descriptions';