CREATE TABLE `SECTOR_NAMES` (
    `SECTOR_NAME_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `SECTOR_ID` INT UNSIGNED NOT NULL,
    `SECTOR_NAME` VARCHAR(255) NOT NULL,
    `SECTOR_NAME_COUNTRY_ISO` VARCHAR(2) NOT NULL,
    `SECTOR_NAME_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `SECTOR_NAME_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `SECTOR_NAME_CREATED_BY` INT NOT NULL,
    `SECTOR_NAME_UPDATED_BY` INT,
    PRIMARY KEY (`SECTOR_NAME_ID`),
    FOREIGN KEY (`SECTOR_ID`) REFERENCES `SECTORS` (`SECTOR_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB COMMENT = 'base table for industry sectors names';