CREATE TABLE `SECTORS` (
    `SECTOR_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `SECTOR_PARENT_ID` INT UNSIGNED,
    `SECTOR_NACE` VARCHAR(255),
    `SECTOR_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `SECTOR_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `SECTOR_CREATED_BY` INT NOT NULL,
    `SECTOR_UPDATED_BY` INT,
    PRIMARY KEY (`SECTOR_ID`)
) ENGINE = INNODB COMMENT = 'base table for industry sectors';