CREATE TABLE `STAKEHOLDER_NAMES` (
    `STAKEHOLDER_NAME_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `STAKEHOLDER_ID` INT UNSIGNED NOT NULL,
    `STAKEHOLDER_NAME` VARCHAR(255) NOT NULL,
    `STAKEHOLDER_NAME_COUNTRY_ISO` VARCHAR(2) NOT NULL,
    `STAKEHOLDER_NAME_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `STAKEHOLDER_NAME_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `STAKEHOLDER_NAME_CREATED_BY` INT NOT NULL,
    `STAKEHOLDER_NAME_UPDATED_BY` INT,
    PRIMARY KEY (`STAKEHOLDER_NAME_ID`),
    FOREIGN KEY (`STAKEHOLDER_ID`) REFERENCES `STAKEHOLDER` (`STAKEHOLDER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB COMMENT = 'base table for industry sectors names';