CREATE TABLE `STAKEHOLDER` (
    `STAKEHOLDER_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `STAKEHOLDER_PARENT_ID` INT UNSIGNED,
    `STAKEHOLDER_NACE` VARCHAR(255),
    `STAKEHOLDER_CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `STAKEHOLDER_UPDATED` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `STAKEHOLDER_CREATED_BY` INT NOT NULL,
    `STAKEHOLDER_UPDATED_BY` INT,
    PRIMARY KEY (`STAKEHOLDER_ID`)
) ENGINE = INNODB COMMENT = 'base table for listing all relevant stakeholder';