CREATE TABLE USER_PASSWORDS (
    USER_PASSWORD_ID INT(10) PRIMARY KEY,
    USER_ID INT(10),
    USER_PASSWORD VARCHAR(255),
    USER_PASSWORD_VALID_FROM DATE,
    USER_PASSWORD_VALID_TO DATE,
    DATA_INSERTED TIMESTAMP,
    DATA_UPDATED TIMESTAMP,
    CONSTRAINT FK_USER_PASSWORDS_USER_ID
        FOREIGN KEY (USER_ID) 
        REFERENCES `USER` (USER_ID)
);

COMMENT ON TABLE USER_PASSWORDS IS 'SIMPLE USER PASSWORD TABLE, ENCRYPTING WITH SHA2';

CREATE INDEX IDX_USER_PASSWORDS_USER_ID ON USER_PASSWORDS (USER_ID);
CREATE INDEX IDX_USER_PASSWORDS_USER_PASSWORD_VALID_TO ON USER_PASSWORDS (USER_PASSWORD_VALID_TO);
