CREATE TABLE USER_GROUP_USERS (
    USER_GROUP_USERS_ID INT PRIMARY KEY,
    USER_GROUP_ID INT(10), 
    USER_ID INT(10) NULL,
    API_USER_ID INT(10) NULL,
    API_CLIENT_ID INT(10) NULL,
    USER_GROUP_USERS_VALID_FROM DATE,
    USER_GROUP_USERS_VALID_TO DATE,
    CREATED_BY VARCHAR(50),
    DATA_INSERTED TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    DATA_UPDATED TIMESTAMP,
    CONSTRAINT FK_USER_GROUP_USERS_USER_ID FOREIGN KEY (USER_ID)
        REFERENCES `USER` (USER_ID)
);

COMMENT ON TABLE USER_GROUP_USERS IS 'RELATIONS BETWEEN GROUPS AND USERS';

CREATE INDEX IDX_UGU_USER_GROUP_ID ON USER_GROUP_USERS (USER_GROUP_ID);
CREATE INDEX IDX_UGU_USER_ID ON USER_GROUP_USERS (USER_ID);
CREATE INDEX IDX_UGU_API_USER_ID ON USER_GROUP_USERS (API_USER_ID);
CREATE INDEX IDX_UGU_API_CLIENT_ID ON USER_GROUP_USERS (API_CLIENT_ID);
CREATE INDEX IDX_UGU_UGU_VALID_TO ON USER_GROUP_USERS (USER_GROUP_USERS_VALID_TO);