CREATE TABLE USER_GROUP_RIGHTS (
    USER_GROUP_RIGHT_ID INT PRIMARY KEY,
    USER_GROUP_ID INT(10),
    USER_OBJECT_ID INT(10),
    USER_GROUP_RIGHT_READ CHAR(1),
    USER_GROUP_RIGHT_WRITE CHAR(1),
    USER_GROUP_RIGHT_EXECUTE CHAR(1),
    USER_GROUP_RIGHT_DELETE CHAR(1),
    USER_GROUP_RIGHT_VALID_FROM DATE,
    USER_GROUP_RIGHT_VALID_TO DATE,
    CREATED_BY VARCHAR(50),
    DATA_INSERTED TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    DATA_UPDATED TIMESTAMP
);

COMMENT ON TABLE USER_GROUP_RIGHTS IS 'RELATION BETWEEN USER GROUPS AND OBJECTS WITH DISTINCT RIGHTS ASSIGNMENT.';

CREATE INDEX IDX_UGR_USER_GROUP_ID ON USER_GROUP_RIGHTS (USER_GROUP_ID);
CREATE INDEX IDX_UGR_USER_OBJECT_ID ON USER_GROUP_RIGHTS (USER_OBJECT_ID);
CREATE INDEX IDX_UGR_UGR_VALID_TO ON USER_GROUP_RIGHTS (USER_GROUP_RIGHT_VALID_TO);
