CREATE TABLE `USER` (
    USER_ID INT(10) PRIMARY KEY,
    USER_PARENT_ID BINARY(16) DEFAULT NULL,
    USER_NAME VARCHAR(255),
    USER_ROLE VARCHAR(255),
    USER_EMAIL VARCHAR(255),
    USER_VALID_FROM DATE,
    USER_VALID_TO DATE,
    DATA_INSERTED TIMESTAMP,
    DATA_UPDATED TIMESTAMP
);

COMMENT ON TABLE `USER` IS 'END USER TABLE';

CREATE INDEX IDX_USER_USER_NAME ON `USER` (USER_NAME);
CREATE INDEX IDX_USER_USER_EMAIL ON `USER` (USER_EMAIL);
CREATE INDEX IDX_USER_USER_VALID_TO ON `USER` (USER_VALID_TO);
