CREATE TABLE USER_DETAILS (
    USER_DETAILS_ID INT PRIMARY KEY,
    USER_ID INT(10),
    USER_DETAILS_SALUTATION VARCHAR(50),
    USER_DETAILS_FIRSTNAME VARCHAR(100),
    USER_DETAILS_LASTNAME VARCHAR(100),
    USER_DETAILS_COMPANY VARCHAR(100),
    USER_DETAILS_BIRTHDAY DATE DEFAULT NULL,
    USER_DETAILS_GENDER VARCHAR(30),
    USER_DETAILS_PHONE VARCHAR(40),
    USER_DETAILS_FAX VARCHAR(40),
    USER_DETAILS_MOBILE VARCHAR(40),
    USER_DETAILS_MOBILE_NOTIFICATION CHAR(1),
    USER_DETAILS_EMAIL VARCHAR(255),
    USER_DETAILS_EMAIL_NOTIFICATION CHAR(1),
    USER_DETAILS_PREFERRED_LANGUAGE CHAR(2) DEFAULT 'EN',
    USER_DETAILS_VALID_FROM DATE,
    USER_DETAILS_VALID_TO DATE,
    CREATED_BY VARCHAR(50),
    DATA_INSERTED TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    DATA_UPDATED TIMESTAMP,
    CONSTRAINT FK_USER_DETAILS_USER_ID
        FOREIGN KEY (USER_ID)
        REFERENCES `USER` (USER_ID)
);

COMMENT ON TABLE USER_DETAILS IS 'TABLE HOLDING USER DETAIL INFORMATION';

CREATE INDEX IDX_UD_USER_ID ON USER_DETAILS (USER_ID);
CREATE INDEX IDX_UD_UD_VALID_TO ON USER_DETAILS (USER_DETAILS_VALID_TO);
