CREATE TABLE USER_RECOVERY_TOKEN (
    USER_RECOVERY_TOKEN_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT(10), 
    USER_RECOVERY_TOKEN VARCHAR(255),
    USER_RECOVERY_TOKEN_VALID_FROM DATE,
    USER_RECOVERY_TOKEN_VALID_TO DATE,
    DATA_INSERTED TIMESTAMP,
    DATA_UPDATED TIMESTAMP
);

COMMENT ON TABLE USER_RECOVERY_TOKEN IS 'TABLE HOLDING USER RELATED TOKENS TO RECOVER PASSWORDS';

CREATE INDEX IDX_USER_RECOVERY_TOKEN_USER_ID ON USER_RECOVERY_TOKEN (USER_ID);
CREATE INDEX IDX_USER_RECOVERY_TOKEN_USER_RECOVERY_TOKEN_VALID_TO ON USER_RECOVERY_TOKEN (USER_RECOVERY_TOKEN_VALID_TO);
