CREATE OR REPLACE VIEW V_ANSWERS_GENERAL_STAKEHOLDER_AVERAGES_CONSOLIDATED AS
    
SELECT
ORG.ORGANISATION_ID,
ORG.ORGANISATION_NAME,
GEN.QUESTIONAIRE_TYPE,
GEN.MEASURE_TOPIC,
GEN.MEASURE_TOPIC_SHORT,
GEN.STAKEHOLDER_ID,
GEN.STAKEHOLDER_PERSPECTIVE,
GEN.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG,
GEN.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
FROM ORGANISATIONS ORG INNER JOIN (
    SELECT
        O.ORGANISATION_ID,
        O.ORGANISATION_NAME,
        ESGQ.QUESTIONAIRE_TYPE,
        CASE
            WHEN SUBSTR(ESG.ESG_MEASURE_KEY,1,1) = 'E'
            THEN 'Mögliche Massnahmen im Bereich Umwelt'
            WHEN SUBSTR(ESG.ESG_MEASURE_KEY,1,1) = 'S'
            THEN 'Mögliche Massnahmen im Bereich Gesellschaft'
            WHEN SUBSTR(ESG.ESG_MEASURE_KEY,1,1) = 'G'
            THEN 'Mögliche Massnahmen im Bereich Wirtschaft'
        END AS MEASURE_TOPIC,
        CASE
            WHEN SUBSTR(ESG.ESG_MEASURE_KEY,1,1) = 'E'
            THEN 'Umwelt'
            WHEN SUBSTR(ESG.ESG_MEASURE_KEY,1,1) = 'S'
            THEN 'Gesellschaft'
            WHEN SUBSTR(ESG.ESG_MEASURE_KEY,1,1) = 'G'
            THEN 'Wirtschaft'
        END AS MEASURE_TOPIC_SHORT,
        ESGA.STAKEHOLDER_ID AS STAKEHOLDER_ID,
        STN.STAKEHOLDER_NAME AS STAKEHOLDER_PERSPECTIVE,
        ROUND(AVG(ESGA.ESG_QUESTIONAIRE_ANSWER_PRIORITY),2) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG,
        ROUND(AVG(ESGA.ESG_QUESTIONAIRE_ANSWER_STATUS),2) AS ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
    FROM ESG_QUESTIONAIRES ESGQ
        INNER JOIN ESG_QUESTIONAIRE_ANSWERS ESGA
        ON ESGQ.ESG_QUESTIONAIRE_ID = ESGA.ESG_QUESTIONAIRE_ID
        INNER JOIN STAKEHOLDER_NAMES STN
        ON STN.STAKEHOLDER_ID = ESGA.STAKEHOLDER_ID
            AND STN.STAKEHOLDER_NAME_COUNTRY_ISO = 'DE'
        INNER JOIN ESG_MEASURES ESG
        ON ESGA.ESG_MEASURE_ID = ESG.ESG_MEASURE_ID
        INNER JOIN ORGANISATIONS O
        ON O.ORGANISATION_ID = ESGQ.ORGANISATION_ID
        INNER JOIN PERSONS P
        ON P.PERSON_ID = ESGQ.PERSON_ID
        INNER JOIN ORGANISATION_PERSONS OP
        ON OP.PERSON_ID = P.PERSON_ID
            AND OP.ORGANISATION_ID=O.ORGANISATION_ID
    WHERE OP.STAKEHOLDER_ID != 8
    AND O.ORGANISATION_ID = 5
    GROUP BY 
        O.ORGANISATION_ID,
        O.ORGANISATION_NAME,
        ESGQ.QUESTIONAIRE_TYPE,
        SUBSTR(ESG.ESG_MEASURE_KEY,1,1),
        ESGA.STAKEHOLDER_ID,
        STN.STAKEHOLDER_NAME
) GEN ON 1 = 1
WHERE ORG.ORGANISATION_ID != 5;