-- analytical view providing average results aggregated on unique organisation ids

CREATE OR REPLACE VIEW V_ANSWERS_ALL_PERSPECTIVES AS
WITH CUSTOMER_ANSWERS_UNPIVOT AS (
		SELECT
			consolidated.ORGANISATION_ID,
			consolidated.ORGANISATION_NAME,
			consolidated.QUESTIONAIRE_TYPE,
			consolidated.ESG_MEASURE_ID,
			consolidated.ESG_MEASURE_KEY,
			ESGM.ESG_MEASURE_DESCRIPTION_SHORT_NAME,
			ESGM.ESG_MEASURE_DESCRIPTION,
			consolidated.STAKEHOLDER_ID,
			consolidated.STAKEHOLDER_PERSPECTIVE,
			consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG,
			consolidated.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
		FROM (
			SELECT
				O.ORGANISATION_ID,
				O.ORGANISATION_NAME,
				ESGQ.QUESTIONAIRE_TYPE,
				ESG.ESG_MEASURE_ID,
				ESG.ESG_MEASURE_KEY,
				ESGA.STAKEHOLDER_ID AS STAKEHOLDER_ID,
				STN.STAKEHOLDER_NAME AS STAKEHOLDER_PERSPECTIVE,
				ROUND(AVG(ESGA.ESG_QUESTIONAIRE_ANSWER_PRIORITY),2) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG,
				ROUND(AVG(ESGA.ESG_QUESTIONAIRE_ANSWER_STATUS),2) AS ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
			FROM ESG_QUESTIONAIRES ESGQ
				INNER JOIN ESG_QUESTIONAIRE_ANSWERS ESGA
				ON ESGQ.ESG_QUESTIONAIRE_ID = ESGA.ESG_QUESTIONAIRE_ID
				INNER JOIN STAKEHOLDER_NAMES STN
				ON STN.STAKEHOLDER_ID = ESGA.STAKEHOLDER_ID
					AND STN.STAKEHOLDER_NAME_COUNTRY_ISO = 'DE'
				INNER JOIN ESG_MEASURES ESG
				ON ESGA.ESG_MEASURE_ID = ESG.ESG_MEASURE_ID
				INNER JOIN ORGANISATIONS O
				ON O.ORGANISATION_ID = ESGQ.ORGANISATION_ID
				INNER JOIN PERSONS P
				ON P.PERSON_ID = ESGQ.PERSON_ID
				INNER JOIN ORGANISATION_PERSONS OP
				ON OP.PERSON_ID = P.PERSON_ID
					AND OP.ORGANISATION_ID=O.ORGANISATION_ID
			WHERE OP.STAKEHOLDER_ID=8
			GROUP BY 
				O.ORGANISATION_ID,
				O.ORGANISATION_NAME,
				ESGQ.QUESTIONAIRE_TYPE,
				ESG.ESG_MEASURE_ID,
				ESG.ESG_MEASURE_KEY,
				ESGA.STAKEHOLDER_ID,
				STN.STAKEHOLDER_NAME
		) consolidated
			INNER JOIN ESG_MEASURE_DESCRIPTIONS ESGM
			ON ESGM.ESG_MEASURE_ID = consolidated.ESG_MEASURE_ID
				AND ESGM.ESG_MEASURE_DESCRIPTION_COUNTRY_ISO = 'DE'

),
OWN_ANSWERS_UNPIVOT AS (
		SELECT
			consolidated.ORGANISATION_ID,
			consolidated.ORGANISATION_NAME,
			consolidated.QUESTIONAIRE_TYPE,
			consolidated.ESG_MEASURE_ID,
			consolidated.ESG_MEASURE_KEY,
			ESGM.ESG_MEASURE_DESCRIPTION_SHORT_NAME,
			ESGM.ESG_MEASURE_DESCRIPTION,
			consolidated.STAKEHOLDER_ID,
			consolidated.STAKEHOLDER_PERSPECTIVE,
			consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG,
			consolidated.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
		FROM (
			SELECT
				O.ORGANISATION_ID,
				O.ORGANISATION_NAME,
				ESGQ.QUESTIONAIRE_TYPE,
				ESG.ESG_MEASURE_ID,
				ESG.ESG_MEASURE_KEY,
				ESGA.STAKEHOLDER_ID AS STAKEHOLDER_ID,
				STN.STAKEHOLDER_NAME AS STAKEHOLDER_PERSPECTIVE,
				ROUND(AVG(ESGA.ESG_QUESTIONAIRE_ANSWER_PRIORITY),2) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG,
				ROUND(AVG(ESGA.ESG_QUESTIONAIRE_ANSWER_STATUS),2) AS ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
			FROM ESG_QUESTIONAIRES ESGQ
				INNER JOIN ESG_QUESTIONAIRE_ANSWERS ESGA
				ON ESGQ.ESG_QUESTIONAIRE_ID = ESGA.ESG_QUESTIONAIRE_ID
				INNER JOIN STAKEHOLDER_NAMES STN
				ON STN.STAKEHOLDER_ID = ESGA.STAKEHOLDER_ID
					AND STN.STAKEHOLDER_NAME_COUNTRY_ISO = 'DE'
				INNER JOIN ESG_MEASURES ESG
				ON ESGA.ESG_MEASURE_ID = ESG.ESG_MEASURE_ID
				INNER JOIN ORGANISATIONS O
				ON O.ORGANISATION_ID = ESGQ.ORGANISATION_ID
				INNER JOIN PERSONS P
				ON P.PERSON_ID = ESGQ.PERSON_ID
				INNER JOIN ORGANISATION_PERSONS OP
				ON OP.PERSON_ID = P.PERSON_ID
					AND OP.ORGANISATION_ID=O.ORGANISATION_ID
			WHERE OP.STAKEHOLDER_ID=8 AND ESGA.STAKEHOLDER_ID = 8
			GROUP BY 
				O.ORGANISATION_ID,
				O.ORGANISATION_NAME,
				ESGQ.QUESTIONAIRE_TYPE,
				ESG.ESG_MEASURE_ID,
				ESG.ESG_MEASURE_KEY,
				ESGA.STAKEHOLDER_ID,
				STN.STAKEHOLDER_NAME
		) consolidated
			INNER JOIN ESG_MEASURE_DESCRIPTIONS ESGM
			ON ESGM.ESG_MEASURE_ID = consolidated.ESG_MEASURE_ID
				AND ESGM.ESG_MEASURE_DESCRIPTION_COUNTRY_ISO = 'DE'

),
STAKEHOLDER_ANSWERS_UNPIVOT AS (
		SELECT
			consolidated.ORGANISATION_ID,
			consolidated.ORGANISATION_NAME,
			consolidated.QUESTIONAIRE_TYPE,
			consolidated.ESG_MEASURE_ID,
			consolidated.ESG_MEASURE_KEY,
			ESGM.ESG_MEASURE_DESCRIPTION_SHORT_NAME,
			ESGM.ESG_MEASURE_DESCRIPTION,
			consolidated.STAKEHOLDER_ID,
			consolidated.STAKEHOLDER_PERSPECTIVE,
			consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG,
			consolidated.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
		FROM (
		SELECT
			O.ORGANISATION_ID,
			O.ORGANISATION_NAME,
			ESGQ.QUESTIONAIRE_TYPE,
			ESG.ESG_MEASURE_ID,
			ESG.ESG_MEASURE_KEY,
			ESGA.STAKEHOLDER_ID AS STAKEHOLDER_ID,
			STN.STAKEHOLDER_NAME AS STAKEHOLDER_PERSPECTIVE,
			ROUND(AVG(ESGA.ESG_QUESTIONAIRE_ANSWER_PRIORITY),2) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG,
			ROUND(AVG(ESGA.ESG_QUESTIONAIRE_ANSWER_STATUS),2) AS ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
		FROM ESG_QUESTIONAIRES ESGQ
			INNER JOIN ESG_QUESTIONAIRE_ANSWERS ESGA
			ON ESGQ.ESG_QUESTIONAIRE_ID = ESGA.ESG_QUESTIONAIRE_ID
			INNER JOIN STAKEHOLDER_NAMES STN
			ON STN.STAKEHOLDER_ID = ESGA.STAKEHOLDER_ID
				AND STN.STAKEHOLDER_NAME_COUNTRY_ISO = 'DE'
			INNER JOIN ESG_MEASURES ESG
			ON ESGA.ESG_MEASURE_ID = ESG.ESG_MEASURE_ID
			INNER JOIN ORGANISATIONS O
			ON O.ORGANISATION_ID = ESGQ.ORGANISATION_ID
			INNER JOIN PERSONS P
			ON P.PERSON_ID = ESGQ.PERSON_ID
			INNER JOIN ORGANISATION_PERSONS OP
			ON OP.PERSON_ID = P.PERSON_ID
				AND OP.ORGANISATION_ID=O.ORGANISATION_ID
		WHERE OP.STAKEHOLDER_ID!=8
        AND O.ORGANISATION_ID=5
		GROUP BY 
			ESGQ.QUESTIONAIRE_TYPE,
			ESG.ESG_MEASURE_ID,
			ESG.ESG_MEASURE_KEY,
			ESGA.STAKEHOLDER_ID,
			STN.STAKEHOLDER_NAME
            
	) consolidated
		INNER JOIN ESG_MEASURE_DESCRIPTIONS ESGM
		ON ESGM.ESG_MEASURE_ID = consolidated.ESG_MEASURE_ID
			AND ESGM.ESG_MEASURE_DESCRIPTION_COUNTRY_ISO = 'DE'

UNION ALL

		SELECT
			consolidated.ORGANISATION_ID,
			consolidated.ORGANISATION_NAME,
			consolidated.QUESTIONAIRE_TYPE,
			consolidated.ESG_MEASURE_ID,
			consolidated.ESG_MEASURE_KEY,
			ESGM.ESG_MEASURE_DESCRIPTION_SHORT_NAME,
			ESGM.ESG_MEASURE_DESCRIPTION,
			consolidated.STAKEHOLDER_ID,
			consolidated.STAKEHOLDER_PERSPECTIVE,
			consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG,
			consolidated.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
	FROM (
		SELECT
			O.ORGANISATION_ID,
			O.ORGANISATION_NAME,
			ESGQ.QUESTIONAIRE_TYPE,
			ESG.ESG_MEASURE_ID,
			ESG.ESG_MEASURE_KEY,
			ESGA.STAKEHOLDER_ID AS STAKEHOLDER_ID,
			STN.STAKEHOLDER_NAME AS STAKEHOLDER_PERSPECTIVE,
			ROUND(AVG(ESGA.ESG_QUESTIONAIRE_ANSWER_PRIORITY),2) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG,
			ROUND(AVG(ESGA.ESG_QUESTIONAIRE_ANSWER_STATUS),2) AS ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
		FROM ESG_QUESTIONAIRES ESGQ
			INNER JOIN ESG_QUESTIONAIRE_ANSWERS ESGA
			ON ESGQ.ESG_QUESTIONAIRE_ID = ESGA.ESG_QUESTIONAIRE_ID
			INNER JOIN STAKEHOLDER_NAMES STN
			ON STN.STAKEHOLDER_ID = ESGA.STAKEHOLDER_ID
				AND STN.STAKEHOLDER_NAME_COUNTRY_ISO = 'DE'
			INNER JOIN ESG_MEASURES ESG
			ON ESGA.ESG_MEASURE_ID = ESG.ESG_MEASURE_ID
			INNER JOIN ORGANISATIONS O
			ON O.ORGANISATION_ID = ESGQ.ORGANISATION_ID
			INNER JOIN PERSONS P
			ON P.PERSON_ID = ESGQ.PERSON_ID
			INNER JOIN ORGANISATION_PERSONS OP
			ON OP.PERSON_ID = P.PERSON_ID
				AND OP.ORGANISATION_ID=O.ORGANISATION_ID
		WHERE OP.STAKEHOLDER_ID!=8
        AND O.ORGANISATION_ID!=5
		GROUP BY 
			O.ORGANISATION_ID,
			O.ORGANISATION_NAME,
			ESGQ.QUESTIONAIRE_TYPE,
			ESG.ESG_MEASURE_ID,
			ESG.ESG_MEASURE_KEY,
			ESGA.STAKEHOLDER_ID,
			STN.STAKEHOLDER_NAME
            
	) consolidated
		INNER JOIN ESG_MEASURE_DESCRIPTIONS ESGM
		ON ESGM.ESG_MEASURE_ID = consolidated.ESG_MEASURE_ID
			AND ESGM.ESG_MEASURE_DESCRIPTION_COUNTRY_ISO = 'DE'

)
SELECT
        CASE
            WHEN SUBSTR(customer.ESG_MEASURE_KEY,1,1) = 'E'
            THEN 'Mögliche Massnahmen im Bereich Umwelt'
            WHEN SUBSTR(customer.ESG_MEASURE_KEY,1,1) = 'S'
            THEN 'Mögliche Massnahmen im Bereich Gesellschaft'
            WHEN SUBSTR(customer.ESG_MEASURE_KEY,1,1) = 'G'
            THEN 'Mögliche Massnahmen im Bereich Wirtschaft'
        END AS MEASURE_TOPIC,
        CASE
            WHEN SUBSTR(customer.ESG_MEASURE_KEY,1,1) = 'E'
            THEN 'Umwelt'
            WHEN SUBSTR(customer.ESG_MEASURE_KEY,1,1) = 'S'
            THEN 'Gesellschaft'
            WHEN SUBSTR(customer.ESG_MEASURE_KEY,1,1) = 'G'
            THEN 'Wirtschaft'
        END AS MEASURE_TOPIC_SHORT,
customer.*,
stakeholder.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG AS STAKEHOLDER_PRIORITY,
stakeholder.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG AS STAKEHOLDER_STATUS,
own.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG AS CUSTOMER_PRIORITY,
own.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG AS CUSTOMER_STATUS
FROM CUSTOMER_ANSWERS_UNPIVOT customer LEFT JOIN STAKEHOLDER_ANSWERS_UNPIVOT stakeholder
ON customer.ESG_MEASURE_ID = stakeholder.ESG_MEASURE_ID AND customer.STAKEHOLDER_ID = stakeholder.STAKEHOLDER_ID
LEFT JOIN OWN_ANSWERS_UNPIVOT own ON own.ESG_MEASURE_ID = customer.ESG_MEASURE_ID;
