-- analytical view providing average results aggregated on unique organisation ids

CREATE OR REPLACE VIEW V_ANSWERS_CUSTOMER_STAKEHOLDER_PERSPECTIVES AS
SELECT
	data.ORGANISATION_ID,
	data.ORGANISATION_NAME,
	data.QUESTIONAIRE_TYPE,
	data.ESG_MEASURE_ID,
	data.ESG_MEASURE_KEY,
	data.ESG_MEASURE_DESCRIPTION_SHORT_NAME,
	data.ESG_MEASURE_DESCRIPTION,
    CASE
        WHEN SUBSTR(data.ESG_MEASURE_KEY,1,1) = 'E'
        THEN 'Mögliche Massnahmen im Bereich Umwelt'
        WHEN SUBSTR(data.ESG_MEASURE_KEY,1,1) = 'S'
        THEN 'Mögliche Massnahmen im Bereich Gesellschaft'
        WHEN SUBSTR(data.ESG_MEASURE_KEY,1,1) = 'G'
        THEN 'Mögliche Massnahmen im Bereich Wirtschaft'
    END AS MEASURE_TOPIC,
    CASE
        WHEN SUBSTR(data.ESG_MEASURE_KEY,1,1) = 'E'
        THEN 'Umwelt'
        WHEN SUBSTR(data.ESG_MEASURE_KEY,1,1) = 'S'
        THEN 'Gesellschaft'
        WHEN SUBSTR(data.ESG_MEASURE_KEY,1,1) = 'G'
        THEN 'Wirtschaft'
    END AS MEASURE_TOPIC_SHORT,
	MAX(ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_MAX,
	SUM(ESG_QUESTIONAIRE_ANSWER_PRIORITY_EMPLOYEES_AVG) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_EMPLOYEES_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_PRIORITY_CLIENTS_AVG) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_CLIENTS_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_PRIORITY_SUPPLIERS_AVG) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_SUPPLIERS_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_PRIORITY_INDUSTRY_REP_AVG) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_INDUSTRY_REP_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_PRIORITY_SOCIETY_AVG) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_SOCIETY_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_PRIORITY_BANK_AVG) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_BANK_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_PRIORITY_REGULATOR_AVG) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_REGULATOR_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_PRIORITY_TERRAMO_AVG) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_TERRAMO_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_PRIORITY_TERRAMO_AVG)*-1 AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_TERRAMO_NEG_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_STATUS_EMPLOYEES_AVG) AS ESG_QUESTIONAIRE_ANSWER_STATUS_EMPLOYEES_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_STATUS_CLIENTS_AVG) AS ESG_QUESTIONAIRE_ANSWER_STATUS_CLIENTS_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_STATUS_SUPPLIERS_AVG) AS ESG_QUESTIONAIRE_ANSWER_STATUS_SUPPLIERS_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_STATUS_INDUSTRY_REP_AVG) AS ESG_QUESTIONAIRE_ANSWER_STATUS_INDUSTRY_REP_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_STATUS_SOCIETY_AVG) AS ESG_QUESTIONAIRE_ANSWER_STATUS_SOCIETY_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_STATUS_BANK_AVG) AS ESG_QUESTIONAIRE_ANSWER_STATUS_BANK_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_STATUS_REGULATOR_AVG) AS ESG_QUESTIONAIRE_ANSWER_STATUS_REGULATOR_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_STATUS_TERRAMO_AVG) AS ESG_QUESTIONAIRE_ANSWER_STATUS_TERRAMO_AVG,
	SUM(ESG_QUESTIONAIRE_ANSWER_STATUS_TERRAMO_AVG)*-1 AS ESG_QUESTIONAIRE_ANSWER_STATUS_TERRAMO_AVG_NEG
FROM
	(
	SELECT
		consolidated.ORGANISATION_ID,
		consolidated.ORGANISATION_NAME,
		consolidated.QUESTIONAIRE_TYPE,
		consolidated.ESG_MEASURE_ID,
		consolidated.ESG_MEASURE_KEY,
		ESGM.ESG_MEASURE_DESCRIPTION_SHORT_NAME,
		ESGM.ESG_MEASURE_DESCRIPTION,
		consolidated.STAKEHOLDER_ID,
		consolidated.STAKEHOLDER_PERSPECTIVE,
		consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 1 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_EMPLOYEES_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 2 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_CLIENTS_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 3 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_SUPPLIERS_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 4 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_INDUSTRY_REP_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 5 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_SOCIETY_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 6 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_BANK_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 7 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_REGULATOR_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 8 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_TERRAMO_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 1 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_STATUS_EMPLOYEES_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 2 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_STATUS_CLIENTS_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 3 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_STATUS_SUPPLIERS_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 4 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_STATUS_INDUSTRY_REP_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 5 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_STATUS_SOCIETY_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 6 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_STATUS_BANK_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 7 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_STATUS_REGULATOR_AVG,
		CASE WHEN consolidated.STAKEHOLDER_ID = 8 THEN
			consolidated.ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
			ELSE 0
		END AS ESG_QUESTIONAIRE_ANSWER_STATUS_TERRAMO_AVG
	FROM (
		SELECT
			O.ORGANISATION_ID,
			O.ORGANISATION_NAME,
			ESGQ.QUESTIONAIRE_TYPE,
			ESG.ESG_MEASURE_ID,
			ESG.ESG_MEASURE_KEY,
			ESGA.STAKEHOLDER_ID AS STAKEHOLDER_ID,
			STN.STAKEHOLDER_NAME AS STAKEHOLDER_PERSPECTIVE,
			ROUND(AVG(ESGA.ESG_QUESTIONAIRE_ANSWER_PRIORITY),2) AS ESG_QUESTIONAIRE_ANSWER_PRIORITY_AVG,
			ROUND(AVG(ESGA.ESG_QUESTIONAIRE_ANSWER_STATUS),2) AS ESG_QUESTIONAIRE_ANSWER_STATUS_AVG
		FROM ESG_QUESTIONAIRES ESGQ
			INNER JOIN ESG_QUESTIONAIRE_ANSWERS ESGA
			ON ESGQ.ESG_QUESTIONAIRE_ID = ESGA.ESG_QUESTIONAIRE_ID
			INNER JOIN STAKEHOLDER_NAMES STN
			ON STN.STAKEHOLDER_ID = ESGA.STAKEHOLDER_ID
				AND STN.STAKEHOLDER_NAME_COUNTRY_ISO = 'DE'
			INNER JOIN ESG_MEASURES ESG
			ON ESGA.ESG_MEASURE_ID = ESG.ESG_MEASURE_ID
			INNER JOIN ORGANISATIONS O
			ON O.ORGANISATION_ID = ESGQ.ORGANISATION_ID
			INNER JOIN PERSONS P
			ON P.PERSON_ID = ESGQ.PERSON_ID
			INNER JOIN ORGANISATION_PERSONS OP
			ON OP.PERSON_ID = P.PERSON_ID
				AND OP.ORGANISATION_ID=O.ORGANISATION_ID
		WHERE OP.STAKEHOLDER_ID=8
		GROUP BY 
			O.ORGANISATION_ID,
			O.ORGANISATION_NAME,
			ESGQ.QUESTIONAIRE_TYPE,
			ESG.ESG_MEASURE_ID,
			ESG.ESG_MEASURE_KEY,
			ESGA.STAKEHOLDER_ID,
			STN.STAKEHOLDER_NAME
	) consolidated
		INNER JOIN ESG_MEASURE_DESCRIPTIONS ESGM
		ON ESGM.ESG_MEASURE_ID = consolidated.ESG_MEASURE_ID
			AND ESGM.ESG_MEASURE_DESCRIPTION_COUNTRY_ISO = 'DE'
) data
GROUP BY
		data.ORGANISATION_ID,
		data.ORGANISATION_NAME,
		data.QUESTIONAIRE_TYPE,
		data.ESG_MEASURE_ID,
		data.ESG_MEASURE_KEY,
		data.ESG_MEASURE_DESCRIPTION;