CREATE OR REPLACE VIEW V_ESG_QUESTIONAIRE_SUMMARY_EN AS
SELECT
    P.PERSON_SALUTATION,
    P.PERSON_FIRSTNAME,
    P.PERSON_LASTNAME,
    OWN_STN.STAKEHOLDER_NAME              AS OWN_PERSPECTIVE,
    P.PERSON_GENDER,
    P.PERSON_BIRTHDAY,
    O.ORGANISATION_NAME,
    ESGQ.ESG_QUESTIONAIRE_ID,
    ESGQ.QUESTIONAIRE_TYPE,
    ESGQ.QUESTIONAIRE_DATE,
    ESGQ.QUESTIONAIRE_COMMENT,
    ESG.ESG_MEASURE_KEY,
    ESGM.ESG_MEASURE_DESCRIPTION,
    STN.STAKEHOLDER_NAME                  AS STAKEHOLDER_PERSPECTIVE,
    ESGA.ESG_QUESTIONAIRE_ANSWER_PRIORITY,
    ESGA.ESG_QUESTIONAIRE_ANSWER_STATUS,
    ESGA.ESG_QUESTIONAIRE_ANSWER_COMMENTS,
    ESGQ.ESG_QUESTIONAIRE_ANSWER_CREATED
FROM
    ESG_QUESTIONAIRES        ESGQ
    INNER JOIN ESG_QUESTIONAIRE_ANSWERS ESGA
    ON ESGQ.ESG_QUESTIONAIRE_ID = ESGA.ESG_QUESTIONAIRE_ID
    INNER JOIN STAKEHOLDER_NAMES STN
    ON STN.STAKEHOLDER_ID = ESGA.STAKEHOLDER_ID
        AND STN.STAKEHOLDER_NAME_COUNTRY_ISO = 'EN'
    INNER JOIN ESG_MEASURES ESG
    ON ESGA.ESG_MEASURE_ID = ESG.ESG_MEASURE_ID
    INNER JOIN ESG_MEASURE_DESCRIPTIONS ESGM
    ON ESGM.ESG_MEASURE_ID = ESG.ESG_MEASURE_ID
        AND ESGM.ESG_MEASURE_DESCRIPTION_COUNTRY_ISO = 'EN'
    INNER JOIN PERSONS P
    ON P.PERSON_ID = ESGQ.PERSON_ID
    INNER JOIN ORGANISATION_PERSONS OP
    ON OP.PERSON_ID = P.PERSON_ID
    LEFT JOIN ORGANISATIONS O
    ON O.ORGANISATION_ID = OP.ORGANISATION_ID
    LEFT JOIN STAKEHOLDER_NAMES OWN_STN
    ON OWN_STN.STAKEHOLDER_ID = OP.STAKEHOLDER_ID
        AND OWN_STN.STAKEHOLDER_NAME_COUNTRY_ISO = 'EN';