CREATE OR REPLACE VIEW V_ESG_QUESTIONAIRE_DUPLICATES AS
SELECT
    PER.PERSON_FIRSTNAME,
    PER.PERSON_LASTNAME,
    PER.PERSON_GENDER,
    PER.PERSON_MAIL,
    DUPLICATES. *,
    E.ESG_QUESTIONAIRE_ID,
    E.QUESTIONAIRE_COMMENT,
    E.ESG_QUESTIONAIRE_ANSWER_CREATED
FROM
    (
        SELECT
        T.QUESTIONAIRE_DATE,
        T.PERSON_ID,
        T.QUESTIONAIRE_TYPE
    FROM
        (
                SELECT
            ESGQ.ESG_QUESTIONAIRE_ID,
            ESGQ.QUESTIONAIRE_TYPE,
            ESGQ.QUESTIONAIRE_DATE,
            ESGQ.QUESTIONAIRE_COMMENT,
            ESGQ.ESG_QUESTIONAIRE_ANSWER_CREATED,
            P.PERSON_ID,
            P.PERSON_FIRSTNAME,
            P.PERSON_LASTNAME,
            STK.STAKEHOLDER_ID,
            STK.STAKEHOLDER_NAME,
            P.PERSON_GENDER,
            P.PERSON_MAIL
        FROM
            ESG_QUESTIONAIRES ESGQ
            INNER JOIN PERSONS P
            ON P.PERSON_ID = ESGQ.PERSON_ID
            INNER JOIN STAKEHOLDER_NAMES STK
            ON STK.STAKEHOLDER_ID = P.STAKEHOLDER_ID
                AND STK.STAKEHOLDER_NAME_COUNTRY_ISO = 'EN'
            ) T
    GROUP BY
            T.QUESTIONAIRE_DATE,
            T.PERSON_ID,
            T.QUESTIONAIRE_TYPE,
            T.STAKEHOLDER_ID
    HAVING
            COUNT(T.ESG_QUESTIONAIRE_ID) > 1
    )                 DUPLICATES
    INNER JOIN PERSONS PER
    ON DUPLICATES.PERSON_ID = PER.PERSON_ID
    INNER JOIN ESG_QUESTIONAIRES E
    ON PER.PERSON_ID = E.PERSON_ID;