INSERT INTO `ESG_MEASURE_DESCRIPTIONS` (
    `ESG_MEASURE_DESCRIPTION_ID`,
    `ESG_MEASURE_ID`,
    `ESG_MEASURE_DESCRIPTION`,
    `ESG_MEASURE_DESCRIPTION_TOPIC`,
    `ESG_MEASURE_DESCRIPTION_ANSWERS`,
    `ESG_MEASURE_DESCRIPTION_COUNTRY_ISO`,
    `ESG_MEASURE_DESCRIPTION_CREATED`,
    `ESG_MEASURE_DESCRIPTION_UPDATED`,
    `ESG_MEASURE_DESCRIPTION_CREATED_BY`,
    `ESG_MEASURE_DESCRIPTION_UPDATED_BY`
) VALUES (
    1,
    1,
    'Possible measures in the area of environment',
    1,
    NULL,
    'EN',
    '2023-12-04 23:18:52',
    NULL,
    1,
    NULL
),
(
    2,
    2,
    'Possible measures in the area of society',
    1,
    NULL,
    'EN',
    '2023-12-04 23:18:52',
    NULL,
    1,
    NULL
),
(
    3,
    3,
    'Possible measures in the area of corporate governance',
    1,
    NULL,
    'EN',
    '2023-12-04 23:19:08',
    NULL,
    1,
    NULL
),
(
    4,
    4,
    'Save electricity or use it more efficiently',
    0,
    NULL,
    'EN',
    '2023-12-04 23:20:42',
    NULL,
    1,
    NULL
),
(
    5,
    5,
    'Increase share of electricity from renewable sources',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    6,
    6,
    'Reduce share of fossil fuels',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    7,
    7,
    'Switch to low-emission vehicles in the vehicle fleet and in logistics',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    8,
    8,
    'Offer products and solutions that allow customers to act more sustainably',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    9,
    9,
    'Use water more efficiently, reduce wastewater',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    10,
    10,
    'Reduce waste and hazardous waste',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    11,
    11,
    'Integrate circular economy principles in product development',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    12,
    12,
    'Switch to environmentally friendly (or friendlier) consumables',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    13,
    13,
    'Train employees to act and work sustainably',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    14,
    14,
    'Introduce ISO14001',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    15,
    15,
    'Build / renovate according to Minergie standard',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    16,
    16,
    'Introduce mobility plan for employees',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    17,
    17,
    'Introduce energy management to monitor and control energy consumption (ISO50001)',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    18,
    18,
    'Making a positive difference with innovative solutions',
    0,
    NULL,
    'EN',
    '2023-12-04 23:25:12',
    NULL,
    1,
    NULL
),
(
    19,
    19,
    'Implement gender balance in management (at least 1/3 each)',
    0,
    NULL,
    'EN',
    '2023-12-04 23:28:12',
    NULL,
    1,
    NULL
),
(
    20,
    20,
    'Conduct regular employee surveys, define goals',
    0,
    NULL,
    'EN',
    '2023-12-04 23:28:12',
    NULL,
    1,
    NULL
),
(
    21,
    21,
    'Improve training and development opportunities for employees',
    0,
    NULL,
    'EN',
    '2023-12-04 23:28:12',
    NULL,
    1,
    NULL
),
(
    22,
    22,
    'Train apprentices and measure and compare training quality',
    0,
    NULL,
    'EN',
    '2023-12-04 23:28:12',
    NULL,
    1,
    NULL
),
(
    23,
    23,
    'Set goals for workplace safety',
    0,
    NULL,
    'EN',
    '2023-12-04 23:28:12',
    NULL,
    1,
    NULL
),
(
    24,
    24,
    'Set goals for community involvement',
    0,
    NULL,
    'EN',
    '2023-12-04 23:28:12',
    NULL,
    1,
    NULL
),
(
    25,
    25,
    'Increase cooperation with suppliers with a high sense of sustainable responsibility',
    0,
    NULL,
    'EN',
    '2023-12-04 23:28:12',
    NULL,
    1,
    NULL
),
(
    26,
    26,
    'Establish clear corporate structure (substitution rules, separation of CEO/VRP, etc.)',
    0,
    NULL,
    'EN',
    '2023-12-04 23:30:53',
    NULL,
    1,
    NULL
),
(
    27,
    27,
    'Align corporate goals and strategies with ESG principles',
    0,
    NULL,
    'EN',
    '2023-12-04 23:30:53',
    NULL,
    1,
    NULL
),
(
    28,
    28,
    'Introduce ESG reporting and communicate openly with stakeholders',
    0,
    NULL,
    'EN',
    '2023-12-04 23:30:53',
    NULL,
    1,
    NULL
),
(
    29,
    29,
    'IT: implement data protection policy, invest in cybersecurity',
    0,
    NULL,
    'EN',
    '2023-12-04 23:30:53',
    NULL,
    1,
    NULL
),
(
    30,
    30,
    'Develop corruption policy',
    0,
    NULL,
    'EN',
    '2023-12-04 23:30:53',
    NULL,
    1,
    NULL
),
(
    31,
    31,
    'Establish code of conduct for suppliers',
    0,
    NULL,
    'EN',
    '2023-12-04 23:30:53',
    NULL,
    1,
    NULL
),
(
    32,
    32,
    'Establish an effective risk management system',
    0,
    NULL,
    'EN',
    '2023-12-04 23:30:53',
    NULL,
    1,
    NULL
),
(
    33,
    33,
    'Establish body to monitor compliance with ESG-relevant laws and guidelines',
    0,
    NULL,
    'EN',
    '2023-12-04 23:30:53',
    NULL,
    1,
    NULL
);

-- german

INSERT INTO `ESG_MEASURE_DESCRIPTIONS` (
    `ESG_MEASURE_ID`,
    `ESG_MEASURE_DESCRIPTION`,
    `ESG_MEASURE_DESCRIPTION_TOPIC`,
    `ESG_MEASURE_DESCRIPTION_ANSWERS`,
    `ESG_MEASURE_DESCRIPTION_COUNTRY_ISO`,
    `ESG_MEASURE_DESCRIPTION_CREATED_BY`,
    `ESG_MEASURE_DESCRIPTION_UPDATED_BY`
) VALUES (
    1,
    'Mögliche Massnahmen im Bereich Umwelt',
    1,
    NULL,
    'DE',
    1,
    NULL
),
(
    2,
    'Mögliche Massnahmen im Bereich Gesellschaft',
    1,
    NULL,
    'DE',
    1,
    NULL
),
(
    3,
    'Mögliche Massnahmen im Bereich Wirtschaft',
    1,
    NULL,
    'DE',
    1,
    NULL
),
(
    4,
    'Strom sparen bzw. effizienter nutzen',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    5,
    'Stromanteil aus erneuerbaren Quellen steigern',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    6,
    'Anteil fossiler Brennstoffe reduzieren',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    7,
    'Auf emissionsarme Fahrzeuge im Fuhrpark und in der Logistik umstellen',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    8,
    'Produkte und Lösungen anbieten, welche es den Kunden erlauben, nachhaltiger zu handeln',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    9,
    'Wasser effizienter nutzen, Abwasser reduzieren',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    10,
    'Abfälle und Sonderabfälle reduzieren',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    11,
    'Kreislaufwirtschaftsprinzipien in der Produktentwicklung integrieren',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    12,
    'Auf umweltfreundliche(re) Verbrauchsmaterialen umstellen',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    13,
    'Mitarbeiter für nachhaltiges Handeln und Arbeiten schulen',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    14,
    'Umweltmanagementsystem einführen (ISO14001)',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    15,
    'Nach Minergie-Standard bauen / sanieren',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    16,
    'Mobilitätsplan für MA einführen',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    17,
    'Energiemanagement zur Überwachung und Steuerung des Energieverbrauchs einführen (ISO50001)',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    18,
    'Mit innovativen Lösungen eine positive Veränderung bewirken',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    19,
    'Ausgewogene Geschlechterverteilung im Management umsetzen (mind. je 1/3)',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    20,
    'Regelmässig Mitarbeiterbefragungen durchführen, Ziele definieren',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    21,
    'Aus- und Weiterbildungsmöglichkeiten für Mitarbeitende verbessern',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    22,
    'Lernende ausbilden und Ausbildungsqualität messen und vergleichen',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    23,
    'Ziele für die Sicherheit am Arbeitsplatz festlegen',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    24,
    'Ziele für das gesellschaftliche Engagement in der Gemeinschaft festlegen',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    25,
    'Vermehrt mit Lieferanten mit hohem nachhaltigen Verantwortungsbewusstsein zusammenarbeiten',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    26,
    'Klare Unternehmensstruktur etablieren (Stellvertreterregelungen, Trennung CEO/VRP, etc.)',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    27,
    'Unternehmensziele und -strategien mit den ESG-Prinzipien im Einklang bringen',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    28,
    'ESG Berichterstattung einführen und offen gegenüber Stakeholdern kommunizieren',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    29,
    'IT: Datenschutzrichtlinie umsetzen, Investition in Cybersicherheit',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    30,
    'Korruptionsrichtlinie erstellen',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    31,
    'Verhaltenskodex für Lieferanten erstellen',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    32,
    'Effektives Risikomanagementsystems einrichten',
    0,
    NULL,
    'DE',
    1,
    NULL
),
(
    33,
    'Gremium zur Überwachung der Einhaltung von ESG-relevanten Gesetzen und Richtlinien einsetzen',
    0,
    NULL,
    'DE',
    1,
    NULL
);